import type { CanvasElement } from '../types/canvas'

/**
 * 测试数据
 * 用于开发和演示
 */
export const mockElements: CanvasElement[] = [
  {
    id: 'rect1',
    type: 'rectangle',
    name: '矩形 1',
    x: 50,
    y: 50,
    width: 100,
    height: 80,
    backgroundColor: '#ff6b6b',
    borderWidth: 2,
    borderColor: '#ff4757'
  },
  {
    id: 'rounded-rect1',
    type: 'rounded-rectangle',
    name: '圆角矩形 1',
    x: 200,
    y: 50,
    width: 120,
    height: 80,
    backgroundColor: '#4ecdc4',
    borderWidth: 3,
    borderColor: '#26d0ce',
    borderRadius: 10
  },
  {
    id: 'circle1',
    type: 'circle',
    name: '圆形 1',
    x: 400,
    y: 50,
    width: 80,
    height: 80,
    backgroundColor: '#45b7d1',
    borderWidth: 2,
    borderColor: '#3a9fbf'
  },
  {
    id: 'triangle1',
    type: 'triangle',
    name: '三角形 1',
    x: 550,
    y: 50,
    width: 100,
    height: 80,
    backgroundColor: '#96ceb4',
    borderWidth: 2,
    borderColor: '#88c5a8'
  },
  {
    id: 'image1',
    type: 'image',
    name: '图片 1',
    x: 50,
    y: 200,
    width: 150,
    height: 100,
    src: '/test1.jpg',
    originalWidth: 150,
    originalHeight: 100,
    filter: 'none'
  },
  {
    id: 'image2',
    type: 'image',
    name: '图片 2',
    x: 220,
    y: 200,
    width: 150,
    height: 100,
    src: '/test1.jpg',
    originalWidth: 150,
    originalHeight: 100,
    filter: 'grayscale',
    filterIntensity: 100
  },
  {
    id: 'image3',
    type: 'image',
    name: '图片 3',
    x: 390,
    y: 200,
    width: 150,
    height: 100,
    src: '/test1.jpg',
    originalWidth: 150,
    originalHeight: 100,
    filter: 'blur',
    filterIntensity: 3
  },
  {
    id: 'image4',
    type: 'image',
    name: '图片 4',
    x: 560,
    y: 200,
    width: 150,
    height: 100,
    src: '/test1.jpg',
    originalWidth: 150,
    originalHeight: 100,
    filter: 'contrast',
    filterIntensity: 150
  },
  {
    id: 'text1',
    type: 'text',
    name: '文本 1',
    x: 50,
    y: 320,
    width: 200,
    height: 50,
    content: 'Bold Text',
    fontFamily: 'Arial, sans-serif',
    fontSize: 24,
    color: '#333333',
    bold: true,
    italic: false,
    underline: false,
    strikethrough: false,
    textAlign: 'left',
    lineHeight: 1.5
  },
  {
    id: 'text2',
    type: 'text',
    name: '文本 2',
    x: 270,
    y: 320,
    width: 200,
    height: 50,
    content: 'Italic Text',
    fontFamily: 'Arial, sans-serif',
    fontSize: 24,
    color: '#333333',
    bold: false,
    italic: true,
    underline: false,
    strikethrough: false,
    textAlign: 'left',
    lineHeight: 1.5
  },
  {
    id: 'text3',
    type: 'text',
    name: '文本 3',
    x: 490,
    y: 320,
    width: 200,
    height: 50,
    content: 'Underline Text',
    fontFamily: 'Arial, sans-serif',
    fontSize: 24,
    color: '#333333',
    bold: false,
    italic: false,
    underline: true,
    strikethrough: false,
    textAlign: 'left',
    lineHeight: 1.5
  },
  {
    id: 'text4',
    type: 'text',
    name: '文本 4',
    x: 50,
    y: 390,
    width: 200,
    height: 50,
    content: 'Strikethrough Text',
    fontFamily: 'Arial, sans-serif',
    fontSize: 24,
    color: '#333333',
    bold: false,
    italic: false,
    underline: false,
    strikethrough: true,
    textAlign: 'left',
    lineHeight: 1.5
  },
  {
    id: 'text5',
    type: 'text',
    name: '文本 5',
    x: 270,
    y: 390,
    width: 200,
    height: 50,
    content: 'Bold & Italic',
    fontFamily: 'Arial, sans-serif',
    fontSize: 24,
    color: '#333333',
    bold: true,
    italic: true,
    underline: false,
    strikethrough: false,
    textAlign: 'left',
    lineHeight: 1.5
  },
  {
    id: 'text6',
    type: 'text',
    name: '文本 6',
    x: 490,
    y: 390,
    width: 200,
    height: 50,
    content: 'All Styles',
    fontFamily: 'Arial, sans-serif',
    fontSize: 24,
    color: '#333333',
    bold: true,
    italic: true,
    underline: true,
    strikethrough: true,
    textAlign: 'left',
    lineHeight: 1.5
  },
  {
    id: 'text7',
    type: 'text',
    name: '文本 7',
    x: 50,
    y: 460,
    width: 200,
    height: 50,
    content: 'Large Font Size',
    fontFamily: 'Arial, sans-serif',
    fontSize: 32,
    color: '#ff6b6b',
    bold: true,
    italic: false,
    underline: false,
    strikethrough: false,
    textAlign: 'left',
    lineHeight: 1.5
  },
  {
    id: 'text8',
    type: 'text',
    name: '文本 8',
    x: 270,
    y: 460,
    width: 200,
    height: 50,
    content: 'Center Aligned',
    fontFamily: 'Arial, sans-serif',
    fontSize: 24,
    color: '#4ecdc4',
    bold: false,
    italic: false,
    underline: false,
    strikethrough: false,
    textAlign: 'center',
    lineHeight: 1.5
  },
  {
    id: 'text9',
    type: 'text',
    name: '文本 9',
    x: 490,
    y: 460,
    width: 200,
    height: 50,
    content: 'Right Aligned',
    fontFamily: 'Arial, sans-serif',
    fontSize: 24,
    color: '#45b7d1',
    bold: false,
    italic: false,
    underline: false,
    strikethrough: false,
    textAlign: 'right',
    lineHeight: 1.5
  }
]

